import type { ContentType, ContentTypeFieldType } from "./types.js";

const TS_TYPE_BY_FIELD: Record<ContentTypeFieldType, string> = {
	text: "string",
	richText: "string",
	number: "number",
	boolean: "boolean",
	date: "string",
	media: "string",
	reference: "string",
	json: "unknown",
};

function pascalCase(name: string): string {
	return name
		.replace(/[^a-zA-Z0-9]+(.)?/g, (_match, char: string | undefined) =>
			char ? char.toUpperCase() : "",
		)
		.replace(/^./, (char) => char.toUpperCase());
}

export function generateContentTypeTypes(contentTypes: ContentType[]): string {
	const interfaces = contentTypes.map((contentType) => {
		const fields = contentType.fields
			.map(
				(field) =>
					`\t${field.key}${field.required ? "" : "?"}: ${TS_TYPE_BY_FIELD[field.type]};`,
			)
			.join("\n");
		return `export interface ${pascalCase(contentType.name)}Fields {\n${fields}\n}`;
	});

	const map = contentTypes
		.map((contentType) => `\t"${contentType._id}": ${pascalCase(contentType.name)}Fields;`)
		.join("\n");

	return (
		[
			"// Generated by `draftbase-sync`. Do not edit by hand.",
			...interfaces,
			`export interface ContentTypeFieldsMap {\n${map}\n}`,
		].join("\n\n") + "\n"
	);
}
